sudo: required
services: 
        - docker

before_install:
        - docker build -t rsilva25/docker-react -f Dockerfile.dev .

script:
        - docker run rsilva25/docker-react npm run test -- --coverage
